apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
  - ../../base
  
namespace: go-db-app-staging


configMapGenerator:
  - name: staging-grafana-dashboards
    files:
      - monitoring/dev-app-canary-slo.json
    options:
      labels:
        grafana_dashboard: "1"  # This should match the grafana side label and labelValues Part in k8s.


patches:
  - target:
      kind: Deployment
      name: go-db-app-version01
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: 23034f5a4e18a04984d83125176ca2fbb75107d7  # Version 01 will be having tested image
      - op: replace
        path: /spec/replicas
        value: 3 # Higher replica count of tested image for staging tests

  # Update Version 02 (The "New" Version being promoted)
  - target:
      kind: Deployment
      name: go-db-app-version02
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: anuroop21/go-app-circleci:ba396be6223f8f5f3b7a88dafe76c92e9cfaa3bf

  - target:
      kind: HTTPRoute
      name: go-app-route-canary-route-staging
    patch: |-
      - op: replace
        path: /spec/rules/0/backendRefs/0/weight
        value: 90

      - op: 
        path: /spec/rules/0/backendRefs/1/weight
        value: 10
