apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: go-db-app-staging

commonLabels:
  env: staging
  managed-by: circleci

patches:
  - target:
      kind: Deployment
      name: go-db-app-version01  # Make sure this matches the name in base/deployment.yaml
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: anuroop21/go-app-circleci:stable-tag

  - target:
      kind: Deployment
      name: go-db-app-version02
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: anuroop21/go-app-circleci:TAG_FROM_CI # This is updated by your promotion job