apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: go-app-kv-secrets
  namespace: go-db-app-dev
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "6313c99e-2b01-40b1-b547-9755dc43cf34"  # ManagedIdentity ClientID
    keyvaultName: "kv-aks-gitops-prod"
    tenantId: "3c744587-46e1-4a41-b95f-3bca3fd5e622"
    objects: |
      array:
        - |
          objectName: DB-HOST
          objectType: secret
        - |
          objectName: DB-NAME
          objectType: secret
        - |
          objectName: DB-USERNAME
          objectType: secret
        - |
          objectName: DB-PASSWORD
          objectType: secret
        - |
          objectName: DB-PORT
          objectType: secret

  secretObjects: # Creates a native K8s secret from Key Vault values
    - secretName: db-creds-k8s
      type: Opaque
      data:
        - objectName: DB-HOST
          key: DB_HOST
        - objectName: DB-NAME
          key: DB_NAME
        - objectName: DB-USERNAME
          key: DB_USERNAME
        - objectName: DB-PASSWORD
          key: DB_PASSWORD
        - objectName: DB-PORT
          key: DB_PORT