{
 "title": "Application logs Dashboards",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "PVC Usage",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "((kubelet_volume_stats_used_bytes / kubelet_volume_stats_capacity_bytes) * 100) * 100",
     "legendFormat": "{{PersistentVolumeClaim}}"
    }
   ]
  },
  {
   "title": "RequestRate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (method) (increase(http_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod restarts",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pod, namespace) (changes(kube_pod_container_status_restarts_total[15m])) > 0",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Top failing operations (Loki)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (operation) (count_over_time({app=\"go-db\"} | json | level=\"ERROR\" [5m]))"
    },
    {
     "direction": "backward",
     "expr": "sum by (operation) (count_over_time({app=\"go-db\"} | json | level=\"INFO\" [5m]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Memory Consumption of the nodes",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg((node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Loki-Error-Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({app=\"go-db\"}| json| level=\"ERROR\"[5m])",
     "legendFormat": "Error_Count"
    }
   ]
  },
  {
   "title": "Pending Pods",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_status_phase{phase=\"Pending\"} > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "K8S Metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "Node CPU Utilization- {{ instance }}"
    },
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100",
     "legendFormat": "MemoryUsage %-{{instance}}"
    },
    {
     "expr": "predict_linear(node_filesystem_free_bytes{mountpoint=\"/\"}[4h], 4 * 3600) < 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (namespace, pod) (increase(container_cpu_cfs_throttled_periods_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RequestRate, AppLatency and DBLatency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum by (version) (rate(http_requests_total[5m]))",
     "legendFormat": "app-{{version}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, version) (rate(http_requests_duration_seconds_bucket[5m])))",
     "legendFormat": "appLatency-{{version}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le, operation) (rate(db_query_duration_seconds_bucket[5m])))",
     "legendFormat": "dbLatency-{{operation}}"
    },
    {
     "expr": "sum by (version) (rate(http_requests_total{status=~\"4..|2..\"}[5m]))",
     "legendFormat": "ErrorRate -{{version}}"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "sum by (method) (sum(rate(http_requests_total[5m])))",
     "legendFormat": "requestRate"
    },
    {
     "expr": "(sum(rate(http_requests_total{status=~\"4..|5..\"}[5m])) / sum(rate(http_requests_total[5m]))) * 100",
     "legendFormat": "ErrorRate"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le, method))",
     "legendFormat": "p95 latency - {{method}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(db_query_duration_seconds_bucket[5m])))",
     "legendFormat": "Overall p95Latency-db"
    },
    {
     "expr": "sum by (operation) (rate(db_errors_total[5m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le, operation) (rate(db_query_duration_seconds_bucket[5m])))",
     "legendFormat": "dbLatency - {{operation}}"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status=~\"4..|5..\"}[5m])) / sum(rate(http_requests_total[5m])) * 100",
     "legendFormat": "TotalErrorRate"
    },
    {
     "expr": "sum by (status) (rate(http_requests_total{status=~\"4..|5..\"}[5m]))",
     "legendFormat": "ErrorRate -{{status}}"
    }
   ]
  },
  {
   "title": "p95 latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, version) (rate(http_request_duration_seconds_bucket[5m])))",
     "legendFormat": "Application-p95Latency-v{{ version }}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le, operation) (rate(db_query_duration_seconds_bucket[5m])))",
     "legendFormat": "dbLatency-{{operation}}"
    },
    {
     "expr": "(\r\n  histogram_quantile(0.95, sum by (le, instance) (rate(http_request_duration_seconds_bucket[5m])))\r\n) \r\n- \r\n(\r\n  histogram_quantile(0.95, sum by (le, instance) (rate(db_query_duration_seconds_bucket[5m])))\r\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}