version: 2.1

executors:
  go-executor:
    docker:
      - image: cimg/go:1.23
  base:
    docker:
      - image: cimg/base:stable
  azure_self_runner:
    machine: true
    resource_class: anuroopps2001/for-aks-rc

jobs:
  build:
    executor: go-executor
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Build application
          working_directory: go-application
          command: |
            go mod tidy
            go build -o app
  
  static-analysis:
    executor: go-executor
    steps:
      - checkout
      - run:
          name: Quality and Vulnerability Scan
          working_directory: go-application
          command: |
            test -z "$(gofmt -l .)"
            go vet ./...
            go install golang.org/x/vuln/cmd/govulncheck@latest
            govulncheck ./... || true

  docker-file-linting:
    executor: base
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true    
      - run:
          name: Lint Dockerfile
          command: docker run --rm -i hadolint/hadolint hadolint --ignore DL3018 - < Docker/Dockerfile

  docker-build-and-push:
    executor: azure_self_runner  # Because Azure keyvault was allowed to access only from the self hosted runner azure vnet subnets
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Build, Scan, and Push
          command: |

            # Login into Azure
            az login --service-principal -u "$AZURE_CLIENT_ID" -t "$AZURE_TENANT_ID" --federated-token "$CIRCLE_OIDC_TOKEN_V2"

            DOCKERHUB_PASS=$(az keyvault secret show --name "DOCKERHUB-PASS" --vault-name "kv-aks-gitops-prod" --query value -o tsv)
            DOCKERHUB_USER=$(az keyvault secret show --name "DOCKERHUB-USER" --vault-name "kv-aks-gitops-prod" --query value -o tsv)

            docker build -f Docker/Dockerfile -t $DOCKERHUB_USER/go-app-circleci:${CIRCLE_SHA1} .
            # Install Trivy
            curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
            ./bin/trivy image --severity HIGH,CRITICAL --ignore-unfixed $DOCKERHUB_USER/go-app-circleci:${CIRCLE_SHA1}
            # Login and Push
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin
            docker push $DOCKERHUB_USER/go-app-circleci:${CIRCLE_SHA1}
            docker tag $DOCKERHUB_USER/go-app-circleci:${CIRCLE_SHA1} $DOCKERHUB_USER/go-app-circleci:latest
            docker push $DOCKERHUB_USER/go-app-circleci:latest

  update_traffic:
    executor: base
    working_directory: ~/project
    parameters:
      v1_weight: { type: string }
      v2_weight: { type: string }
    steps:
      - checkout
      - run:
          name: Update Kustomize Dev Overlay
          command: |
            cd gitops-repo/overlays/dev

            git fetch origin feature/circleci-metrics
            git reset --mixed origin/feature/circleci-metrics

            
            sed -i "/go-db-app-version02/,/value:/ s|value: .*|value: anuroop21/go-app-circleci:${CIRCLE_SHA1}|" kustomization.yaml   # update version deployment with the newly built tag

            sed -i "/backendRefs\/0/,/value:/ s|value: .*|value: << parameters.v1_weight >>|" kustomization.yaml
            sed -i "/backendRefs\/1/,/value:/ s|value: .*|value: << parameters.v2_weight >>|" kustomization.yaml

            git fetch origin feature/circleci-metrics
            git reset --mixed origin/feature/circleci-metrics
            
            git config user.name "circleCI"
            git config user.email "ci@circleci.com"

            git add kustomization.yaml
            
            # Only commit if changes exist to avoid empty commit errors
            if ! git diff --cached --quiet; then
              git commit -m "Update Traffic from << parameters.v1_weight >> to << parameters.v2_weight >> [skip ci]"
              git push origin feature/circleci-metrics
            else
              echo "No changes detected, skipping push."
            fi

  wait_for_rollout:
    executor: azure_self_runner
    steps:
      - checkout
      - run:
          name: Authenticate AKS and Wait
          command: |
            az login --service-principal -u "$AZURE_CLIENT_ID" -t "$AZURE_TENANT_ID" --federated-token "$CIRCLE_OIDC_TOKEN_V2"
            az aks get-credentials -g rg-aks-southindia --name aks-private-india
            kubectl rollout status deployment/go-db-app-version02 -n go-db-app-dev  --timeout=60s

  canary_check:
    machine: true
    resource_class: anuroopps2001/for-aks-rc
    parameters:
      v1_rollback_weight: { type: string }
      v2_rollback_weight: { type: string }
    steps:
      - checkout
      - run:
          name: Prometheus SLO Check
          command: |
            sleep 30s
            export PROMETHEUS_URL="http://10.1.1.7:9090"
            python3 k8s/observability/prometheus-grafana-alertting-with-helm/slo/scripts/canary_check.py
      - run:
          name: Rollback on Failure
          when: on_fail
          command: |
            cd gitops-repo/overlays/dev
            # Standard Git Rollback logic using sed
            sed -i "/go-db-service-sample-version-01/,/weight:/ s|weight: .*|weight: 100|" kustomization.yaml
            sed -i "/go-db-service-sample-version-02/,/weight:/ s|weight: .*|weight: 0|" kustomization.yaml

            git config user.name "circleCI"
            git config user.email "ci@circleci.com"
            git add kustomization.yaml
            git commit -m "Rollback triggered [skip ci]"
            git push origin feature/circleci-metrics

  promote:
    executor: base
    working_directory: ~/project 
    steps:
      - checkout 
      - run:
          name: Shift Stable Image (v2 -> v1)
          command: |
            cd gitops-repo/overlays/dev

            git fetch origin feature/circleci-metrics
            git reset --mixed origin/feature/circleci-metrics

            # Target only the version01 block and update its image to the current SHA 100% tested version02 
            sed -i "/go-db-app-version01/,/value:/ s|value: .*|value: anuroop21/go-app-circleci:${CIRCLE_SHA1}|" kustomization.yaml
            
            sed -i "/backendRefs\/0/,/value:/ s|value: .*|value: 100|" kustomization.yaml
            sed -i "/backendRefs\/1/,/value:/ s|value: .*|value: 0|" kustomization.yaml

            git config user.name "circleCI"
            git config user.email "ci@circleci.com"
            git add kustomization.yaml
            git commit -m "Promote: ${CIRCLE_SHA1} moved to v1 [skip ci]"
            git push origin feature/circleci-metrics

  create_staging_pr:
    executor: azure_self_runner  # Again, Azure keyVault access allowed only from the self hosted runner subnet
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Create Staging Promotion PR via API
          command: |

            # Login into Azure
            az login --service-principal -u "$AZURE-CLIENT-ID" -t "$AZURE-TENANT-ID" --federated-token "$CIRCLE_OIDC_TOKEN_V2"

            GITHUB_TOKEN=$(az keyvault secret show --name "GITHUB-TOKEN" --vault-name "kv-aks-gitops-prod" --query value -o tsv)

            git config user.email "ci@circle.com"
            git config user.name "circleci"
            
            BRANCH_NAME="promote-${CIRCLE_SHA1:0:7}"
            echo "export BRANCH=$BRANCH_NAME" >> $BASH_ENV
            
            # Branching directly from staging to ensure a clean PR
            git fetch origin staging
            git checkout -b $BRANCH_NAME origin/staging

            # Apply image change to Staging Kustomize Overlay and This keeps Version 01 (Stable) untouched while you test the new SHA in Version 02
            cd gitops-repo/overlays/staging
            sed -i "/go-db-app-version02/,/value:/ s|value: .*|value: anuroop21/go-app-circleci:${CIRCLE_SHA1}|" kustomization.yaml
            
            # Also, ensure weights in Staging are reset for the new test (e.g., 90/10
            sed -i "/backendRefs\/0/,/value:/ s|value: .*|value: 90|" kustomization.yaml
            sed -i "/backendRefs\/1/,/value:/ s|value: .*|value: 10|" kustomization.yaml
            
            git add kustomization.yaml
            git commit -m "Promote to Staging: ${CIRCLE_SHA1} [skip ci]"
            git push -f origin $BRANCH_NAME
            
            # GitHub CLI creates the PR (Ensure GITHUB_TOKEN is in Env Vars)
            curl -L \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${GITHUB_TOKEN}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/anuroopps2001/go-db-application/pulls \
              -d "{
                \"title\":\"🚀 Promote Dev to Staging: ${CIRCLE_SHA1:0:7}\",
                \"body\":\"Automated promotion from feature/circleci-metrics to staging. Tested and promoted by CircleCI.\",
                \"head\":\"$BRANCH_NAME\",
                \"base\":\"staging\"
              }"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: feature/circleci-metrics

      - static-analysis:
          filters:
            branches:
              only: feature/circleci-metrics

      - docker-file-linting:
          filters:
            branches:
              only: feature/circleci-metrics

      - docker-build-and-push:
          requires: [build, static-analysis, docker-file-linting]

      - update_traffic:
          name: traffic_10
          v1_weight: "90"
          v2_weight: "10"
          requires: [docker-build-and-push]

      - wait_for_rollout:
          requires: [traffic_10]

      - canary_check:
          name: check_10
          v1_rollback_weight: "100"
          v2_rollback_weight: "0"
          requires: [wait_for_rollout]

      - approve_50:
          type: approval
          requires: [check_10]

      - update_traffic:
          name: traffic_50
          v1_weight: "50"
          v2_weight: "50"
          requires: [approve_50]

      - canary_check:
          name: check_50
          v1_rollback_weight: "100"
          v2_rollback_weight: "0"
          requires: [traffic_50]

      - approve_100:
          type: approval
          requires: [check_50]

      - update_traffic:
          name: traffic_100
          v1_weight: "0"
          v2_weight: "100"
          requires: [approve_100]

      - promote:
          type: approval
          requires: [traffic_100]

      - approve_staging:
          type: approval
          requires: [promote]

      - create_staging_pr:
          requires: [approve_staging]