apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: go-db-project
  namespace: argocd
spec:
  description: Project for go-db application

  sourceRepos:
    - https://github.com/anuroopps2001/go-db-application

  destinations:
    - namespace: default
      server: https://kubernetes.default.svc
  clusterResourceWhitelist: []

  namespaceResourceWhitelist:
    - group: apps
      kind: Deployment
    - group: ""
      kind: Service
    - group: ""
      kind: ConfigMap
    - group: ""
      kind: Secret
