apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: go-app-kv-secrets
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "bb4dc99e-8ee2-43c4-9ac5-1a64c16e16d9"  # ManagedIdentity ClientID
    keyvaultName: "anuroop-kv-1q0c"
    tenantId: "e0358252-0a91-43bc-9f97-69a7d2f53ce1"
    objects: |
      array:
        - |
          objectName: DB-HOST
          objectType: secret
        - |
          objectName: DB-NAME
          objectType: secret
        - |
          objectName: DB-USERNAME
          objectType: secret
        - |
          objectName: DB-PASSWORD
          objectType: secret
        - |
          objectName: DB-PORT
          objectType: secret

  secretObjects: # Creates a native K8s secret from Key Vault values
    - secretName: db-creds-k8s
      type: Opaque
      data:
        - objectName: DB-HOST
          key: DB_HOST
        - objectName: DB-NAME
          key: DB_NAME
        - objectName: DB-USERNAME
          key: DB_USERNAME
        - objectName: DB-PASSWORD
          key: DB_PASSWORD
        - objectName: DB-PORT
          key: DB_PORT