apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-db-app-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/anuroopps2001/go-db-application.git
    targetRevision: staging # Watches your feature branch
    path: gitops-repo/overlays/staging # Points to the Dev Kustomize folder
  destination:
    server: https://kubernetes.default.svc
    namespace: go-db-app-staging # Must match the namespace in kustomization.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true # ArgoCD will create the namespace if it doesn't exist