apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: go-db-app-dev

# Kustomize will find EVERY deployment using this image and update the tag
images:
  - name: anuroop21/go-app-circleci
    newTag: "SET_BY_CIRCLECI" 

patches:
  - target:
      kind: HTTPRoute
      name: go-app-route-canary-route
    patch: |-
      - op: replace
        path: /spec/rules/0/backendRefs/0/weight
        value: 100
      - op: replace
        path: /spec/rules/0/backendRefs/1/weight
        value: 0