apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# This file tells ArgoCD: "Take everything in Base, but apply these Dev-specific rules."

# Points to your newly organized base
resources:
  - ../../base

# Forces all resources (Deployments, Services, etc.) into the Dev namespace
namespace: go-db-app-dev


# Target ONLY v2 to give it the new image from CircleCI
patches:
  - target:
      kind: Deployment
      name: go-db-app-version01
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: anuroop21/go-app-circleci:ef89658572f08899eb95a322e41aa205a953f38d  # Keep any old stable tags

  - target:
      kind: Deployment
      name: go-db-app-version02
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: anuroop21/go-app-circleci:1082b3caf75628e5c225b2ca6130cc64e344e454

  - target:
      kind: HTTPRoute
      name: go-app-route-canary-route
    patch: |-
      - op: replace
        path: /spec/rules/0/backendRefs/0/weight
        value: 90

      - op: replace
        path: /spec/rules/0/backendRefs/1/weight
        value: 10